modLoader="javafml"
loaderVersion="[1,)"
license="MIT"

[[mods]]
modId="moderninhibited"
version="${version}"
displayName="ModernInhibited"
authors="Team Potato"
description='''

'''

[[mixins]]
config = "moderninhibited.mixins.json"